/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Competitions: () => import('#controllers/competitions_controller'),
  Fitbit: () => import('#controllers/fitbit_controller'),
  FitbitWebhook: () => import('#controllers/fitbit_webhook_controller'),
  Friends: () => import('#controllers/friends_controller'),
  Google: () => import('#controllers/google_controller'),
  GoogleWebhook: () => import('#controllers/google_webhook_controller'),
  Profiles: () => import('#controllers/profiles_controller'),
};
