/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm';
import { DateTime } from 'luxon';

export class ActivityStepSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'date',
    'granularity',
    'id',
    'providerAccountId',
    'steps',
    'syncedAt',
    'time',
    'updatedAt',
  ] as const;
  $columns = ActivityStepSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column.date()
  declare date: DateTime;
  @column()
  declare granularity: string;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare providerAccountId: number;
  @column()
  declare steps: number;
  @column.dateTime()
  declare syncedAt: DateTime;
  @column()
  declare time: string | null;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
}

export class CompetitionMemberSchema extends BaseModel {
  static $columns = [
    'competitionId',
    'createdAt',
    'id',
    'invitedBy',
    'status',
    'updatedAt',
    'userId',
  ] as const;
  $columns = CompetitionMemberSchema.$columns;
  @column()
  declare competitionId: number;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare invitedBy: number | null;
  @column()
  declare status: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
  @column()
  declare userId: number;
}

export class CompetitionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'createdBy',
    'deletedAt',
    'description',
    'endDate',
    'goalType',
    'goalValue',
    'id',
    'name',
    'startDate',
    'status',
    'teamId',
    'updatedAt',
    'visibility',
  ] as const;
  $columns = CompetitionSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column()
  declare createdBy: number;
  @column.dateTime()
  declare deletedAt: DateTime | null;
  @column()
  declare description: string | null;
  @column.date()
  declare endDate: DateTime;
  @column()
  declare goalType: string;
  @column()
  declare goalValue: number | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare name: string;
  @column.date()
  declare startDate: DateTime;
  @column()
  declare status: string;
  @column()
  declare teamId: number | null;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
  @column()
  declare visibility: string;
}

export class DailyStepSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'date',
    'id',
    'primaryProviderAccountId',
    'steps',
    'updatedAt',
    'userId',
  ] as const;
  $columns = DailyStepSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column.date()
  declare date: DateTime;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare primaryProviderAccountId: number | null;
  @column()
  declare steps: number;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
  @column()
  declare userId: number;
}

export class FitbitSubscriptionSchema extends BaseModel {
  static $columns = [
    'collectionType',
    'createdAt',
    'fitbitSubscriberId',
    'id',
    'isActive',
    'providerAccountId',
    'subscriptionId',
    'updatedAt',
    'userId',
  ] as const;
  $columns = FitbitSubscriptionSchema.$columns;
  @column()
  declare collectionType: string;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column()
  declare fitbitSubscriberId: string | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare isActive: boolean | null;
  @column()
  declare providerAccountId: number;
  @column()
  declare subscriptionId: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
  @column()
  declare userId: number;
}

export class FriendshipSchema extends BaseModel {
  static $columns = ['createdAt', 'friendId', 'id', 'status', 'updatedAt', 'userId'] as const;
  $columns = FriendshipSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare friendId: number;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare status: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare userId: number;
}

export class ProviderAccountSchema extends BaseModel {
  static $columns = [
    'accessToken',
    'createdAt',
    'expiresAt',
    'healthUserId',
    'id',
    'providerId',
    'providerUserId',
    'refreshToken',
    'updatedAt',
    'userId',
  ] as const;
  $columns = ProviderAccountSchema.$columns;
  @column()
  declare accessToken: string | null;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column.dateTime()
  declare expiresAt: DateTime | null;
  @column()
  declare healthUserId: string | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare providerId: number;
  @column()
  declare providerUserId: string;
  @column()
  declare refreshToken: string | null;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
  @column()
  declare userId: number;
}

export class ProviderSchema extends BaseModel {
  static $columns = ['createdAt', 'displayName', 'id', 'name', 'updatedAt'] as const;
  $columns = ProviderSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column()
  declare displayName: string;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare name: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
}

export class QueueJobSchema extends BaseModel {
  static $columns = [
    'acquiredAt',
    'data',
    'error',
    'executeAt',
    'finishedAt',
    'id',
    'queue',
    'score',
    'status',
    'workerId',
  ] as const;
  $columns = QueueJobSchema.$columns;
  @column()
  declare acquiredAt: bigint | number | null;
  @column()
  declare data: string;
  @column()
  declare error: string | null;
  @column()
  declare executeAt: bigint | number | null;
  @column()
  declare finishedAt: bigint | number | null;
  @column({ isPrimary: true })
  declare id: string;
  @column()
  declare queue: string;
  @column()
  declare score: bigint | number | null;
  @column()
  declare status: string;
  @column()
  declare workerId: string | null;
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'cronExpression',
    'everyMs',
    'fromDate',
    'id',
    'lastRunAt',
    'name',
    'nextRunAt',
    'payload',
    'runCount',
    'runLimit',
    'status',
    'timezone',
    'toDate',
  ] as const;
  $columns = QueueScheduleSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column()
  declare cronExpression: string | null;
  @column()
  declare everyMs: bigint | number | null;
  @column.dateTime()
  declare fromDate: DateTime | null;
  @column({ isPrimary: true })
  declare id: string;
  @column.dateTime()
  declare lastRunAt: DateTime | null;
  @column()
  declare name: string;
  @column.dateTime()
  declare nextRunAt: DateTime | null;
  @column()
  declare payload: string;
  @column()
  declare runCount: number;
  @column()
  declare runLimit: number | null;
  @column()
  declare status: string;
  @column()
  declare timezone: string;
  @column.dateTime()
  declare toDate: DateTime | null;
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const;
  $columns = RememberMeTokenSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column.dateTime()
  declare expiresAt: DateTime;
  @column()
  declare hash: string;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare tokenableId: number;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'preferredStepsProviderId',
    'updatedAt',
  ] as const;
  $columns = UserSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column()
  declare email: string;
  @column()
  declare fullName: string | null;
  @column({ isPrimary: true })
  declare id: number;
  @column({ serializeAs: null })
  declare password: string;
  @column()
  declare preferredStepsProviderId: number | null;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}
